LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := kernel-modules.x80power.rc
LOCAL_VENDOR_MODULE := true
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_RELATIVE_PATH := init
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := surface3_defconfig
LOCAL_MODULE_CLASS := FAKE
LOCAL_SRC_FILE := surface3_defconfig
include $(BUILD_SYSTEM)/base_rules.mk

$(LOCAL_BUILT_MODULE): $(LOCAL_PATH)/$(LOCAL_SRC_FILE) $(TARGET_FIRMWARE_KERNEL_DEFCONFIG)
	cat $^ > $@

TARGET_KERNEL_DEFCONFIG := $(LOCAL_BUILT_MODULE)
